### ISSUE TITLE
Bad error handling when failure

### ISSUE THREAD

**Issue by wookayin** [amq92/simple_slurm#17]
```
>>> slurm.sbatch('echo demo.py ' + Slurm.SLURM_ARRAY_TASK_ID)

File ".../site-packages/simple_slurm/core.py", line 131, in sbatch
    assert success_msg in stdout, result.stderr
AssertionError: None
```

It does not show what's exactly wrong and what happened from the sbatch command's output.

E.g.,
```
sbatch: error: Invalid generic resource (gres) specification
```

**Comment by wookayin** [comment]
Also, when --verbose is given, it should print the stdout output before dying due to AssertionError.

**Comment by amq92** [comment]
Currently the `subprocess.run` only redirects the `stdout` but not the `stderr` so any error message should have been printed even before the `assert` is reached ! **It this not the case for you ?** Could you post the entire Traceback ?

This explains why the assertion message is `None`, as it was never captured by the `run` command.
A simple fix would be [`result = subprocess.run(cmd, shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)`](https://github.com/amq92/simple_slurm/blob/8a163388cd4a65a9e8d39347db5cb2e9d6190920/simple_slurm/core.py#L128)

If indeed you have not seen any `stderr` message, your case is most interesting.
Could you please share a MWE of your script ? Also, could you execute it using the "normal" procedure (i.e. without `simple_slurm` with your own shell script) to see what the output should be ?

I'll hold off on making the update till after reviewing your case, as it may be more complicated than a simple redirection.

Here's an example with a wrong `gres` specification :
```python
from simple_slurm import Slurm

slurm = Slurm(array=range(-1), verbose=True)
slurm.sbatch('echo $HOSTNAME')
```
Using `python`
```bash
$ python demo.py
sbatch: error: Invalid generic resource (gres) specification   #  < ---- error shown here
Traceback (most recent call last):
  File "demo.py", line 4, in <module>
    slurm.sbatch('echo $HOSTNAME')
  File "[...]/simple_slurm/core.py", line 131, in sbatch
    assert success_msg in stdout, result.stderr
AssertionError: None    # <------- not very clear message ! :S
```
Using interactive `python`
```bash
$ ipython
In [1]: %run demo.py
sbatch: error: Invalid generic resource (gres) specification
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
File /gpfs_new/data/users/amendoza/home/Documents/simple_slurm/demo.py:4
      1 from simple_slurm import Slurm
      3 slurm = Slurm(gres='xxx')
----> 4 slurm.sbatch('echo $HOSTNAME')

File /gpfs_new/data/users/amendoza/home/Documents/simple_slurm/simple_slurm/core.py:131, in Slurm.sbatch(self, run_cmd, convert, verbose, sbatch_cmd, shell)
    129 success_msg = 'Submitted batch job'
    130 stdout = result.stdout.decode('utf-8')
--> 131 assert success_msg in stdout, result.stderr
    132 if verbose:
    133     print(stdout)

AssertionError: None
```
