### ISSUE TITLE
simple-slurm doesn't work with PyInstaller

### ISSUE THREAD

**Issue by cvpsmith** [amq92/simple_slurm#26]
Running Python 3.12 in a venv with simple-slurm module installed.  Ubuntu 24.04 (and Debian 12).  I can run python3 program.py and it imports simple_slurm just fine, but when I create and executable using PyInstaller (same venv), I get the following error:

`(env) user@host:~/dev/myprog/source$ dist/myprog
Traceback (most recent call last):
  File "myprog.py", line 14, in <module>
    from simple_slurm import Slurm
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 378, in exec_module
  File "simple_slurm/__init__.py", line 7, in <module>
  File "simple_slurm/core.py", line 30, in __init__
  File "simple_slurm/core.py", line 224, in read_simple_txt
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/_MEI6Tpwvi/simple_slurm/arguments.txt'
[PYI-1200370:ERROR] Failed to execute script 'myprog' due to unhandled exception!`

I've tried to get it to work on multiple systems, but I get a similar error.  Pip list shows that it's installed:

`(env) user@host:~/dev/myprog/source$ pip list
Package                   Version
------------------------- -------
altgraph                  0.17.4
packaging                 24.1
pip                       24.0
pyinstaller               6.10.0
pyinstaller-hooks-contrib 2024.8
setuptools                75.1.0
simple-slurm              0.2.7
(env) user@host:~/dev/myprog/source`

Any help would be MUCH appreciated!

**Comment by amq92** [comment]
It seems that PyInstaller doesn't automatically bundle `.txt` files like `arguments.txt` by default.
I've slightly updated the `setup.py` but I think you still need to update your build.

The following code was suggested by an AI LLM and correctly identifyes all files in `datas` 

1. Create a hook file (`hooks/hook-simple_slurm.py`)
    ```python
    from PyInstaller.utils.hooks import collect_data_files
    datas = collect_data_files("simple_slurm", includes=["**/*.txt"])
    ```
2. Build with hooks
    ```bash
    pyinstaller --additional-hooks-dir=hooks --name=your_app your_main_script.py  
    ```
